# Generated by Django 4.2.2 on 2023-10-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiryapi', '0002_alter_enquirydatas_mobilenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='enquirydatas',
            name='Interested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquiryapi.product'),
        ),
    ]
