# Generated by Django 4.2.2 on 2023-10-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiryapi', '0003_product_alter_enquirydatas_interested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquirydatas',
            old_name='Interested',
            new_name='Interesteds',
        ),
    ]
