# Generated by Django 4.2.2 on 2023-10-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiryapi', '0004_rename_interested_enquirydatas_interesteds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirydatas',
            name='Interesteds',
        ),
    ]
