# Generated by Django 4.2.2 on 2023-10-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiryapi', '0005_remove_enquirydatas_interesteds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='enquiryDatas',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
