# Generated by Django 4.2.2 on 2023-10-07 12:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Enquiryapi', '0006_delete_enquirydatas_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='enquiryDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('OrganizationName', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('MobileNumber', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('Location', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('Interesteds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquiryapi.product')),
            ],
        ),
    ]
