# Generated by Django 4.2.2 on 2023-10-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiryapi', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirydatas',
            name='Interesteds',
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='Interesteds',
            field=models.ManyToManyField(to='Enquiryapi.product'),
        ),
    ]
